name: test
on: [push, pull_request]
jobs:
  check-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: echo "This is a dummy test"
